copy 10080_gds-ms-api\.env app\gds-ms-api\.env
copy 10085_gds-terminal\.env app\gds-terminal\.env
copy 10086_gds-lrts\.env app\gds-lrts\.env
copy 13000_gds-logger\.env app\gds-logger\.env
copy 13001_authentication-module\.env app\authentication-module\.env
copy 13002_school-module\.env app\school-module\.env
copy 13003_file-service\.env app\file-service\.env
copy 13004_export-service\.env app\export-service\.env
copy 13005_time-service\.env app\time-service\.env
copy 13006_import-service\.env app\import-service\.env